version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: tuyen
      MYSQL_PASSWORD: secret
      MYSQL_TABLE: todo_list
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret 
    networks:
      - wpsite
      
  # Wordpress
  # To access localhost:8000 showing wordpress, need to modify the info in wp-config.php after docker-compose
  # Or override it by my available modified wp-config.php file in the ./compose-config/ after your compose
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: tuyen
      WORDPRESS_DB_PASSWORD: secret
    networks:
      - wpsite
      
    # PHP image
    # Showing structured todo_list table by entering localhost:9090 address
  php-app:
    depends_on:
      - db
    # Need to build my-php-app image by the Dockerfile in the ./my-php-image/ before docker-compose
    image: my-php-app:latest
    ports:
      - '9090:80'
    restart: always
    environment:
      APP_USER: tuyen
      APP_PASSWORD: secret
      APP_DATABASE: mydatabase
      APP_TABLE: todo_list
    networks:
      - wpsite  
      
networks:
  wpsite:
volumes:
  db_data:

